# Generated by Django 2.0.6 on 2018-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('collegeId', models.IntegerField(unique=True)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('level', models.IntegerField(choices=[(1, '双一流'), (2, '一本'), (3, '二本'), (4, '三本')], verbose_name='学校级别')),
                ('area', models.PositiveIntegerField(null=True)),
                ('academyNum', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'collegeInfo',
                'verbose_name_plural': 'collegeInfos',
                'db_table': 'imagination_collegeInfo',
                'ordering': ['collegeId'],
                'get_latest_by': 'collegeId',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.AlterIndexTogether(
            name='collegeinfo',
            index_together={('name', 'collegeId')},
        ),
    ]
