# Generated by Django 2.0.6 on 2018-08-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('academyId', models.IntegerField(unique=True)),
                ('majorNum', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'academyInfo',
                'verbose_name_plural': 'academyInfos',
                'ordering': ['academyId'],
            },
        ),
        migrations.CreateModel(
            name='ClasssInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classsId', models.IntegerField(unique=True)),
                ('studentNum', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'classsInfo',
                'verbose_name_plural': 'classsInfos',
                'ordering': ['classsId'],
            },
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.IntegerField(unique=True)),
                ('classsNum', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'gradeInfo',
                'verbose_name_plural': 'gradeInfos',
                'ordering': ['gradeId'],
            },
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('majorId', models.IntegerField(unique=True)),
                ('gradeNum', models.PositiveIntegerField()),
                ('academyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagination.AcademyInfo')),
            ],
            options={
                'verbose_name': 'majorInfo',
                'verbose_name_plural': 'majorInfos',
                'ordering': ['majorId'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('namePinYin', models.CharField(max_length=20)),
                ('idCardNum', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('year_in_college', models.DateTimeField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bust', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('hips', models.IntegerField()),
                ('hobbies', models.CharField(max_length=200)),
                ('married', models.BooleanField()),
                ('classsInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagination.ClasssInfo')),
            ],
            options={
                'verbose_name': 'studentInfo',
                'verbose_name_plural': 'studentInfos',
                'ordering': ['studentId'],
            },
        ),
        migrations.AlterModelOptions(
            name='collegeinfo',
            options={'default_permissions': ('add', 'change', 'delete'), 'managed': True, 'ordering': ['collegeId'], 'verbose_name': 'collegeInfo', 'verbose_name_plural': 'collegeInfos'},
        ),
        migrations.AddField(
            model_name='gradeinfo',
            name='majorInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagination.MajorInfo'),
        ),
        migrations.AddField(
            model_name='classsinfo',
            name='gradeInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagination.GradeInfo'),
        ),
        migrations.AddField(
            model_name='academyinfo',
            name='collegeInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagination.CollegeInfo'),
        ),
        migrations.AlterIndexTogether(
            name='studentinfo',
            index_together={('name', 'studentId')},
        ),
        migrations.AlterIndexTogether(
            name='majorinfo',
            index_together={('name', 'majorId')},
        ),
        migrations.AlterIndexTogether(
            name='academyinfo',
            index_together={('name', 'academyId')},
        ),
    ]
